# Generated by Django 3.2.16 on 2022-12-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('company_name', models.CharField(max_length=30)),
                ('acc_holder_name', models.CharField(max_length=20)),
                ('ifsc', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=30)),
                ('acc_number', models.BigIntegerField()),
                ('seller_pic', models.ImageField(upload_to='seller/')),
            ],
        ),
    ]
